### ISSUE TITLE
cannot import name 'LANGUAGES' from 'voxpopuli'

### ISSUE THREAD

**Issue by wiamfa** [facebookresearch/voxpopuli#32]
when i run in google colab !python /content/voxpopuli/voxpopuli/download_audios.py --subset asr in google colab , it gives me the following error :
raceback (most recent call last):
  File "/content/voxpopuli/voxpopuli/download_audios.py", line 13, in <module>
    from voxpopuli import LANGUAGES, LANGUAGES_V2, YEARS, DOWNLOAD_BASE_URL
ImportError: cannot import name 'LANGUAGES' from 'voxpopuli' (/usr/local/lib/python3.7/dist-packages/voxpopuli/__init__.py)

**Comment by kahne** [comment]
Hi @wiamfa , please use `%cd /content/voxpopuli` and `!python -m voxpopuli.download_audios` instead to resolve the importing issue.

**Comment by wiamfa** [comment]
@kahne  thanks it  works.
